# Dimensionality Reduction 

#### 1. Why is Dimensionality Reduction Needed?

#### 2. Methods of Dimensionality Reduction

###### (A) Feature Selection

In [4]:
from sklearn.feature_selection import VarianceThreshold
import pandas as pd
df = pd.DataFrame({'Feature1': [1, 1, 1, 1, 1], 'Feature2': [1, 2, 3, 4, 5]})
vt=VarianceThreshold(threshold=0.1)
df.iloc[:,vt.fit(df).get_support()]

,Feature2
0,1
1,2
2,3
3,4
4,5


In [5]:
corr_matrix=df.corr()
corr_matrix

,Feature1,Feature2
Feature1,NaN,NaN
Feature2,NaN,1.0


###### (B) Feature Extraction (Transforming Features)

In [12]:
from sklearn.decomposition import PCA
import numpy as np
data = np.array([[2.5, 2.4], [0.5, 0.7], [2.2, 2.9], [1.9, 2.2], [3.1, 3.0], [2.3, 2.7], [2, 1.6], [1, 1.1], [1.5, 1.6], [1.1, 0.9]])
df = pd.DataFrame(data, columns=['Feature1', 'Feature2'])
pca=PCA(n_components=1)
df_pca=pca.fit_transform(df)
df_pca

array([[-0.82797019],
       [ 1.77758033],
       [-0.99219749],
       [-0.27421042],
       [-1.67580142],
       [-0.9129491 ],
       [ 0.09910944],
       [ 1.14457216],
       [ 0.43804614],
       [ 1.22382056]])

In [18]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
df['Label'] = [0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
lda=D=LDA(n_components=1)
lda_features=lda.fit_transform(df[['Feature1','Feature2']],df['Label'])
lda_features

array([[-1.25353005],
       [ 2.05173951],
       [ 0.1280127 ],
       [ 0.1017372 ],
       [-2.13952455],
       [-0.37160761],
       [-0.86715586],
       [ 1.19609257],
       [ 0.45776382],
       [ 0.69647226]])

In [27]:
from sklearn.manifold import TSNE
tsne=TSNE(n_components=1)
feature_tsne=tsne.fit_transform(df[['Feature1','Feature2']])
feature_tsne

C:\Users\polro\anaconda3\lib\site-packages\sklearn\manifold\_t_sne.py:780: FutureWarning: The default initialization in TSNE will change from 'random' to 'pca' in 1.2.
  warnings.warn(
C:\Users\polro\anaconda3\lib\site-packages\sklearn\manifold\_t_sne.py:790: FutureWarning: The default learning rate in TSNE will change from 200.0 to 'auto' in 1.2.
  warnings.warn(


array([[ -428.10757],
       [  497.03204],
       [ 1163.751  ],
       [ -749.10004],
       [ 1566.4912 ],
       [  188.5373 ],
       [  817.8428 ],
       [-1095.2501 ],
       [-1498.2516 ],
       [ -119.54968]], dtype=float32)