In [1]:
import numpy as np

In [3]:
array=np.array([10,20,30,40,50])
print(array)

[10 20 30 40 50]


In [4]:
list=[1,2,3,4,5,6,7,8,9,10]
arr=np.array(list)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
#type
type(arr)

numpy.ndarray

In [6]:
#two diamensional array
arr1=np.array([[9,8,7,6],[1,2,3,4]])
arr1

array([[9, 8, 7, 6],
       [1, 2, 3, 4]])

In [7]:
# shape
arr1.shape

(2, 4)

In [8]:
#reshape
arr2=np.array([10,20,70,45,23,67])
arr2
arr2.reshape(2,3)

array([[10, 20, 70],
       [45, 23, 67]])

In [9]:
# get type
arr2.dtype

dtype('int32')

In [10]:
#dimension
arr2.ndim

1

In [11]:
arr1.ndim

2

In [12]:
# total number of elements
arr1.size

8

In [13]:
arr2.size

6

In [14]:
# get item size
arr1.itemsize

4

In [15]:
# get total itemsize 
arr1.nbytes

32

In [18]:
a=np.array([[34,5,6,45,75,43],[23,57,78,54,12,98],[234,56,43,67,46,34]])
a

array([[ 34,   5,   6,  45,  75,  43],
       [ 23,  57,  78,  54,  12,  98],
       [234,  56,  43,  67,  46,  34]])

In [20]:
# get the elements[r,c]
a[1,3]

54

In [27]:
# numpy array of strings
z=np.array(["Rohan","bablu","Husen","Mahesh"])
z

array(['Rohan', 'bablu', 'Husen', 'Mahesh'], dtype='<U6')

In [28]:
z[2]

'Husen'

In [30]:
z.reshape(2,2)

array([['Rohan', 'bablu'],
       ['Husen', 'Mahesh']], dtype='<U6')

In [33]:
z.shape

(4,)

In [50]:
#access the all elements
a[:,:]

array([[100, 200, 100, 100, 100, 100],
       [ 23,  57,  78,  54,  12,  98],
       [234,  56,  43,  67,  46,  34]])

In [37]:
# acces the 1 row and all columns
a[0,:]

array([34,  5,  6, 45, 75, 43])

In [41]:
#acces startindex,endindex:stepsize
a[1,::2]

array([23, 78, 12])

In [48]:
#update the elements
a[0,1]=200
a

array([[100, 200, 100, 100, 100, 100],
       [ 23,  57,  78,  54,  12,  98],
       [234,  56,  43,  67,  46,  34]])

In [52]:
a[0,3]=999

In [54]:
a

array([[100, 200, 100, 999, 100, 100],
       [ 23,  57,  78,  54,  12,  98],
       [234,  56,  43,  67,  46,  34]])

In [57]:
a[:,4]=69
a

array([[100, 200, 100, 999,  69, 100],
       [ 23,  57,  78,  54,  69,  98],
       [234,  56,  43,  67,  69,  34]])

In [61]:
a[1,:]=[1,2,3,4,5,6]
a

array([[100, 200, 100, 999,  69, 100],
       [  1,   2,   3,   4,   5,   6],
       [234,  56,  43,  67,  69,  34]])

In [63]:
# 3rd array

In [3]:
arr3=np.array([[[10,20],[99,69]],[[45,34],[67,45]]])
arr3

array([[[10, 20],
        [99, 69]],

       [[45, 34],
        [67, 45]]])

In [7]:
m=np.array([[[12,23],[2,78]],[[26,74],[89,67]]])
m

array([[[12, 23],
        [ 2, 78]],

       [[26, 74],
        [89, 67]]])

In [8]:
#acces the 3 diamenesional array
m[0,:,:]

array([[12, 23],
       [ 2, 78]])

In [10]:
# initializing of matrix

In [12]:
# all 0s matrix
r=np.zeros((2,3))
r

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
r=np.zeros((3,2),dtype='int32')
r

array([[0, 0],
       [0, 0],
       [0, 0]])

In [5]:
c=np.ones((2,3))
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
c=np.ones((2,3),dtype="int32")
c

array([[1, 1, 1],
       [1, 1, 1]])

In [10]:
d=np.full((3,2),34)
d

array([[34, 34],
       [34, 34],
       [34, 34]])

In [14]:
d=np.full_like(d,69)
d

array([[69, 69],
       [69, 69],
       [69, 69]])

In [16]:
# random 
np.random.rand(3,2)

array([[0.77188994, 0.48914309],
       [0.68708126, 0.84553001],
       [0.97565525, 0.71669196]])

In [20]:
# random integers
np.random.randint(2,9,size=(2,5))

array([[6, 8, 3, 6, 5],
       [5, 8, 7, 3, 8]])

In [22]:
# identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [2]:
#mathameatical operations 

In [4]:
a=np.array([2,5,7,4,9])
a+2

array([ 4,  7,  9,  6, 11])

In [6]:
a-2

array([0, 3, 5, 2, 7])

In [8]:
a*4

array([ 8, 20, 28, 16, 36])

In [10]:
a/4

array([0.5 , 1.25, 1.75, 1.  , 2.25])

In [12]:
a**2

array([ 4, 25, 49, 16, 81], dtype=int32)

In [14]:
a%2

array([0, 1, 1, 0, 1], dtype=int32)

In [20]:
# addition of two matrix
l=np.array([[12,34,56,44],[23,56,78,54]])
m=np.array([[23,12,45,64],[34,43,54,33]])
print(l)
print(m)

[[12 34 56 44]
 [23 56 78 54]]
[[23 12 45 64]
 [34 43 54 33]]


In [23]:
l+m

array([[ 35,  46, 101, 108],
       [ 57,  99, 132,  87]])

In [24]:
# trignometric functions 

In [26]:
np.sin(a)

array([ 0.90929743, -0.95892427,  0.6569866 , -0.7568025 ,  0.41211849])

In [28]:
np.cos(a)

array([-0.41614684,  0.28366219,  0.75390225, -0.65364362, -0.91113026])

In [30]:
np.tan(a)

array([-2.18503986, -3.38051501,  0.87144798,  1.15782128, -0.45231566])

In [35]:
np.tan(a)

array([-2.18503986, -3.38051501,  0.87144798,  1.15782128, -0.45231566])

In [39]:
np.sin(a[1])

-0.9589242746631385

In [44]:
# linera algbra
x=np.array([[12,23,56,34],[45,76,34,56]])
y=np.array([[12,33],[23,45],[12,34],[32,23]])
print(x)
print(y)

[[12 23 56 34]
 [45 76 34 56]]
[[12 33]
 [23 45]
 [12 34]
 [32 23]]


In [56]:
#matrix multiplication
f=np.matmul(x,y)
f

array([[2433, 4117],
       [4488, 7349]])

In [58]:
# determinant of matrix  
np.linalg.det(f)

-596978.9999999997

In [67]:
np.linalg.eig(f)

(array([ -60.6522495, 9842.6522495]),
 array([[-0.85533587, -0.4856904 ],
        [ 0.51807389, -0.87413091]]))

In [65]:
#stastical functions
a=np.array([[1,34,23,56],[45,23,12,43]])
a

array([[ 1, 34, 23, 56],
       [45, 23, 12, 43]])

In [69]:
# mininmun
np.min(a)

1

In [71]:
#maximum
np.max(a)

56

In [75]:
# row wise minmum
np.min(a,axis=1)

array([ 1, 12])

In [78]:
# column wise minimum
np.min(a,axis=0)

array([ 1, 23, 12, 43])

In [84]:
# column wise maximum
np.max(a,axis=0)

array([45, 34, 23, 56])

In [87]:
#row wise maximum
np.max(a,axis=1)

array([56, 45])

In [90]:
np.max(a)

56

In [92]:
#sum
np.sum(a)

237

In [94]:
# sum of row
np.sum(a,axis=1)

array([114, 123])

In [96]:
# sum of column
np.sum(a,axis=0)

array([46, 57, 35, 99])

In [98]:
# mean
np.mean(a)

29.625

In [101]:
#median
np.median(a)

28.5

In [105]:
# standard deviation
np.std(a)

17.13138567075063

In [106]:
# variance
np.var(a)

293.484375