creating a numpy array

In [1]:
import numpy as np

In [2]:
x=np.array([10,20,30,40,50])
print(x)
print(type(x))

[10 20 30 40 50]
<class 'numpy.ndarray'>


## l=[]
for i in range(1,5):
    listDataFromUser=int(input("Enter a number: "))
    l.append(listDataFromUser)
    
print(np.array(l))    

# Types of array

In [6]:
Array_1D=np.array([10,20,30,40,50])
print(Array_1D)
print(Array_1D.ndim)

[10 20 30 40 50]
1


In [ ]:
Array_2D=np.array([[10,20,30,40,50],[11,22,33,44,55],[90,91,92,93,94]])
print(Array_2D)
print(Array_2D.ndim)

In [ ]:
Array_3D=np.array([[[10,20],[99,88],[11,22]]])
print(Array_3D)
print(Array_3D.ndim)

In [ ]:
M_Array=np.array([1,2,3,4], ndmin=10)
print(M_Array)
print(M_Array.ndim)

# zeros


In [ ]:
#one diamension with zeros
arr_zeros=np.zeros(3)
print(arr_zeros)

In [ ]:
# two diamension array with zeros
tdim_arr_zeros=np.zeros((3,2))
print(tdim_arr_zeros)

# ones

In [ ]:
arr=np.ones([2,4])
print(arr)

# empty

In [ ]:
empty_arr=np.empty(3)
print(empty_arr)

# arange

In [ ]:
range_array=np.arange(4)
print(range_array)

r=np.arange(2,6)
print(r)

# diagonal

In [ ]:
dia=np.eye(4)
print(dia)
d=np.eye(3)
print(d)

# linspace

In [ ]:
arr_linspace=np.linspace(0,20,num=5)
print(arr_linspace)

# Random

# 1] rand

In [ ]:
import numpy as np
rand=np.random.rand(5)
print(rand)
r=np.random.rand(3,3)
print(r)

# 2] randn

In [ ]:
randn=np.random.randn(5)
print(randn)

# 3] ranf

In [ ]:
ranf=np.random.ranf(5)
print(ranf)

# 4] randint

In [ ]:
randint=np.random.randint(2,30,6)
print(randint)

# Datatypes in numpy


In [ ]:
datatype=np.array([10 ,20 ,30, 40, 50])
print(datatype)
print(datatype.dtype)
dt=np.array(["Rohan","bablu","husen","mahesh"])
print(dt)
print(dt.dtype)

In [ ]:
dt=np.array([1,2,3,4,5], dtype="int8")
print(dt)
print(dt.dtype)

In [ ]:
dt=np.array([11,22,33,44,55],dtype="f")
print(dt)
print(dt.dtype)

In [ ]:
old_arr=np.array([10,20,30,40,50])
print(old_arr)
print(old_arr.dtype)
new_arr=np.float32(old_arr)
print(new_arr)

In [ ]:
o_arr=np.array([10,20,30])
print(o_arr)
print(o_arr.dtype)
n_arr=o_arr.astype(float)
print(n_arr)
print(n_arr.dtype)

# shape

In [ ]:
var=np.array([[1,2,3,4],[11,33,44,55]])
print(var)
print(var.ndim)
print(var.shape)

# reshape

In [ ]:
var1=np.array([111,22,33,44,55,66,77,88,99])
print(var1)
print(var1.ndim)
var2=var1.reshape(3,3)
print(var2)
print(var2.ndim)

# Arithmetic operation

In [ ]:
var1=np.array([2,4,5,6])
var2=np.array([2,3,4,3])
var3=var1+var2
print(var3)
var4=np.add(var1,var2)
print(var4)

In [ ]:
x=np.array([11,22,33,44,55])
y=np.add(x,4)
print(y)

# 2D array

In [ ]:
x=np.array([[2,3,4,5],[3,2,5,6]])
print(x)
y=np.array([[3,2,5,4],[3,5,4,2]])
print()
print(y)
print()
z=np.add(x,y)
print(z)

# min

In [ ]:
x=np.array([11,34,45,23,53,65,75,34])
minimum=np.min(x)
print(minimum)

In [ ]:
x=np.array([[12,34,54,54,98],[45,43,67,34,65]])
print(x)
minimum=np.min(x,axis=1)
print(minimum)

# max

In [ ]:
maximum=np.max(x)
print(maximum)

In [ ]:
maximum=np.max(x,axis=1)
print("max: ",maximum,np.argmax(maximum))

# sqrt

In [ ]:
sqrt=np.sqrt(x)
print(sqrt)

# indexing

In [12]:
var1=np.array([11,22,33,44,55])
print(var1)
print(var1[3])
print(var1.ndim)
print(var1.shape)


[11 22 33 44 55]
44
1
(5,)


In [16]:
var2=np.array([[11,22,33],[99,88,77]])
print(var2)
print(var2[1][2])
print(var2.ndim)
print(var2.shape)

[[11 22 33]
 [99 88 77]]
77
2
(2, 3)


# slicing

In [22]:
x=np.array([11,22,33,44,55,66,77,88])
print(x)
print()
print("33 to 66",x[2:6])
print(x[:])
print(x[4:])


[11 22 33 44 55 66 77 88]

33 to 66 [33 44 55 66]
[11 22 33 44 55 66 77 88]
[55 66 77 88]


In [32]:
two_dim=np.array([[11,22,33,44,55],[99,88,77,66,55]])
print(two_dim)
print()
print("88 to 55: ",two_dim[1,1:])

[[11 22 33 44 55]
 [99 88 77 66 55]]

88 to 55:  [88 77 66 55]


# iteration

In [34]:
elements=np.array([11,22,33,44,55,66,77,88,99])
print(elements)
for i in elements:
    print(i)

[11 22 33 44 55 66 77 88 99]
11
22
33
44
55
66
77
88
99


In [39]:
elem=np.array([[11,22,33,44,55],[99,88,77,66,55]])
print(elem)
print()

for i in elem:
    for j in i:
        print(j)

[[11 22 33 44 55]
 [99 88 77 66 55]]

11
22
33
44
55
99
88
77
66
55


In [44]:
z=np.array([[[11,22,33],[44,55,66],[99,88,77]]])
print(z)
print(z.ndim)
for i in np.nditer(z):
 print(i)

[[[11 22 33]
  [44 55 66]
  [99 88 77]]]
3
11
22
33
44
55
66
99
88
77


In [48]:
for i,d in np.ndenumerate(z):
    print(i,d)

(0, 0, 0) 11
(0, 0, 1) 22
(0, 0, 2) 33
(0, 1, 0) 44
(0, 1, 1) 55
(0, 1, 2) 66
(0, 2, 0) 99
(0, 2, 1) 88
(0, 2, 2) 77


# copy vs view

In [73]:
original_arr=np.array([11,22,33,44,55,66,77,88,99])
original_arr[4]=78
c=original_arr.copy()
print("original array",original_arr)
print("copy array: ",c)


original array [11 22 33 44 78 66 77 88 99]
copy array:  [11 22 33 44 78 66 77 88 99]


In [3]:
o_array=np.array([1,2,3,4,5,6,7,8,9])
print(o_array)
v=o_array.view()
o_array[2]=69

print(v)


[1 2 3 4 5 6 7 8 9]
[ 1  2 69  4  5  6  7  8  9]


# concatinate

In [7]:
var=np.array([1,2,3,4,5])
var1=np.array([11,22,33,44,55])
new_var=np.concatenate((var,var1))
print(var)
print()
print(var1)
print()
print(new_var)

[1 2 3 4 5]

[11 22 33 44 55]

[ 1  2  3  4  5 11 22 33 44 55]


In [10]:
var=np.array([[1,2,3],[11,22,33],[34,34,23]])
var1=np.array([[99,88,77],[45,34,76],[98,67,45]])
new_var=np.concatenate((var,var1),axis=1)
new_var1=np.concatenate((var,var1),axis=0)
print(var)
print()
print(var1)
print()
print(new_var)
print()
print(new_var1)

[[ 1  2  3]
 [11 22 33]
 [34 34 23]]

[[99 88 77]
 [45 34 76]
 [98 67 45]]

[[ 1  2  3 99 88 77]
 [11 22 33 45 34 76]
 [34 34 23 98 67 45]]

[[ 1  2  3]
 [11 22 33]
 [34 34 23]
 [99 88 77]
 [45 34 76]
 [98 67 45]]


# split

In [14]:
x=np.array([11,22,33,44,55,66])
s=np.split(x,3)
print(x)
print()
print(s)

[11 22 33 44 55 66]

[array([11, 22]), array([33, 44]), array([55, 66])]


In [19]:
y=np.array([[11,22,33],[44,55,66],[77,88,99]])
s=np.split(y,3)
print(y)
print()
print(s)
print(type(s))

[[11 22 33]
 [44 55 66]
 [77 88 99]]

[array([[11, 22, 33]]), array([[44, 55, 66]]), array([[77, 88, 99]])]
<class 'list'>


# search

In [3]:
var=np.array([11,22,33,44,55,55,22,33])
s=np.where(var==22)
print(s)

(array([1, 6], dtype=int64),)


# sort

In [7]:
x=np.array([12,76,45,98,25,74,56,34])
s=np.sort(x)
print(s)

[12 25 34 45 56 74 76 98]


# filter

In [10]:
var_3=np.array(["c","b","h","r","e"])
f=[True,False,False,True,True]
new_a=var_3[f]
print(new_a)

['c' 'r' 'e']


# shuffle

In [ ]:
# a=np.array([1,2,3,4,5,6,7,8,9])
np.random.shuffle(a)
print(a)

# unique

In [20]:
a=np.array([11,22,22,33,22,66,55,44,66,77,55,77])
x=np.unique(a,return_index=True,return_counts=True)
print(x)

(array([11, 22, 33, 44, 55, 66, 77]), array([0, 1, 3, 7, 6, 5, 9], dtype=int64), array([1, 3, 1, 1, 2, 2, 2], dtype=int64))


# resize

In [21]:
a=np.array([11,22,33,44,55,66,77,88,99])
r=np.resize(a,(3,3))
print(r)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


# flatten

In [24]:
f=r.flatten()
print(f)

[11 22 33 44 55 66 77 88 99]


# insert

In [29]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a)
b=np.insert(a,3,69)
print(b)

[1 2 3 4 5 6 7 8 9]
[ 1  2  3 69  4  5  6  7  8  9]


# delete

In [31]:
a=np.array([1,2,3,4,5])
b=np.delete(a,1)
print(b)

[1 3 4 5]
